# frozen_string_literal: true

# Fixes Jekyll "destination is shared by multiple files" warnings and, more
# importantly, incomplete tag/category archive pages:
#
# 1. Taxonomy normalization
#    Case/format variants of the same tag ("Security" vs "security",
#    "Web Development" vs "web-development", "Ruby on Rails" vs "ruby-on-rails")
#    all slugify to the SAME archive URL. jekyll-archives then builds one
#    archive page per variant, each holding only a SUBSET of the posts, racing
#    to write the same destination. Canonicalize every tag/category to its
#    slug form at read time so all posts for one tag land on a single,
#    complete archive page. Tags that slugify to an empty string (e.g. CJK)
#    are left untouched.
#
# 2. Theme-gem override cleanup
#    The Chirpy theme gem ships assets/404.html and assets/feed.xml which
#    collide with this site's own root 404.html page and the feed generated by
#    jekyll-feed. The site's files win on write, but Jekyll emits a conflict
#    warning for 50+ destinations. Drop the theme-gem duplicates after read.
Jekyll::Hooks.register :site, :post_read do |site|
  site.posts.docs.each do |doc|
    %w[tags categories].each do |key|
      next unless doc.data[key]

      normalized = Array(doc.data[key]).map do |value|
        str = value.to_s
        slug = Jekyll::Utils.slugify(str)
        slug.empty? ? str : slug
      end
      doc.data[key] = normalized.uniq
    end
  end

  %w[assets/404.html assets/feed.xml].each do |path|
    site.pages.reject! { |page| page.path.to_s == path }
    site.static_files.reject! { |file| file.relative_path.to_s == "/#{path}" }
  end
end